### ISSUE TITLE
Cannot update secure settings permission

### ISSUE THREAD

**Issue by ssmith353** [simonesestito/nougat_quickSettings#22]
Device: Pixel 3, Android 9.0 Nov Update. Run on Mac os Mojave 10.14.1

adb shell pm grant it.simonesestito.ntiles android.permission.WRITE_SECURE_SETTING

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown permission: android.permission.WRITE_SECURE_SETTING
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1398)
	at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2093)
	at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5411)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1730)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:217)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21330)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
	at android.os.Binder.execTransact(Binder.java:731)

**Comment by simonesestito** [comment]
Hi. The right command is adb shell pm grant it.simonesestito.ntiles android.permission.**WRITE_SECURE_SETTINGS**

**Comment by simonesestito** [comment]
That's not the right place to ask those questions, I'll close the Issue
