### ISSUE TITLE
Don't believe it's working

### ISSUE THREAD

**Issue by Baugh30** [simonesestito/nougat_quickSettings#24]
Build version: 7.3 
Build date: 1979-11-30 00:00:00 
Current date: 2019-03-03 01:18:31 
Device: Samsung SM-N960U 
 
Stack trace:  
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@f4dbc65 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1040)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at android.app.Dialog.show(Dialog.java:469)
	at androidx.appcompat.app.b$a.d(Unknown Source:4)
	at it.simonesestito.ntiles.a$n.a(Unknown Source:42)
	at it.simonesestito.ntiles.ui.a.a$b.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7327)
	at android.view.View.performClickInternal(View.java:7299)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27774)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by simonesestito** [comment]
Please send me an email with more information about what were you doing

**Comment by simonesestito** [comment]
Closed because this thread is intended only for issues related to translation files

**Comment by MOSSSKITO** [comment]
@Baugh30
