### ISSUE TITLE
Crash on Android 10/Q

### ISSUE THREAD

**Issue by captainhook** [simonesestito/nougat_quickSettings#30]
Occurs when trying to toggle the 'Caffeine' switch from tiles. I have not tested with anything else yet.

```
Build version: 7.3 
Build date: 1979-11-30 00:00:00 
Current date: 2019-12-08 22:32:11 
Device: Google Pixel 3 XL 
 
Stack trace:  
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=it.simonesestito.ntiles/.backend.services.CaffeineService }: app is in background uid UidRecord{a25bc75 u0a219 CEM  idle change:cached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
	at android.app.ContextImpl.startService(ContextImpl.java:1571)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at it.simonesestito.ntiles.Caffeine.a(Unknown Source:41)
	at it.simonesestito.ntiles.b.b.onClick(Unknown Source:14)
	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:431)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by simonesestito** [comment]
Closed because this GitHub repo is not for issues about the app. It's all about string translations
